version: "3"
services:
  redis:
    build: 
      context: ./redis
      dockerfile: Dockerfile.dev
    networks:
      - backend
    volumes:
      - ./data:/data
    restart: unless-stopped
  nginx:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile.dev
    networks:
      - backend
    ports:
      - "85:80"
    restart: unless-stopped
  gs_calc:
    build:
      context: ./gs_calc
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
      - nginx
    networks:
      - backend
    restart: unless-stopped
  home:
    build:
      context: ./main_page
      dockerfile: Dockerfile.dev
    depends_on:
      - nginx
      - gs_calc
    networks:
      - backend
    restart: unless-stopped
networks:
  backend: